name = "PaddedViews"
uuid = "5432bcbf-9aad-5242-b902-cca2824c8663"
version = "0.5.12"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "0.10, 0.11, 1"
julia = "0.7, 1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Test"]
